jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2.3.1 #pulls code from my machine
      - run: dotnet build #compile
  test:
  # needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test -p:CollectCoverage=true # unit testing

  analyze:
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: action/checkout@v2.3.1
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: | #multiline value with each line ending with a newline character \n
          dotnet sonarscanner begin -o:'devinhorton271' -k:'DevinHorton271_YAML' -d:sonar.login='3131007a1fd85069ce22d05617c1df1ba1f57458' -d:sonar.host.url='https://sonarcloud.io'
          dotnet build
          dotnet test -p:CollectCoverage=true
          dotnet sonarscanner end -d:sonar.login='3131007a1fd85069ce22d05617c1df1ba1f57458'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: cibuild

on: push








# person: # object
#   firstName: "name" #string
#   lastName: 100 #number
#   middlename: true #boolean
#   alias:
#     - "dotnet" #-indicates a collection
#     - "lead"
#     - subAlias:
